### ISSUE TITLE
Usage of the BatchQuery and QueryAll Operations

### ISSUE THREAD

**Issue by mikependon** [ademolguner/RepoDbExample#1]
Hi, I saw in your code that you post-process the data in the client. You can actually improve this query.

https://github.com/ademolguner/RepoDbExample/blob/ce1222c83dcc6007a7e4da395cab5fa6037f3eca/RepoDbExample/RepoDbExample.Core/DataAccess/RepoDb/DbRepositoryBase.cs#L57

Using this one.

```csharp
List<TEntity> data = conn.QueryAll<TEntity>(rows: count).AsList();
```

I would highly recommend to always use the `AsList()` extended method over `ToList()`. It try to cast first if the objects are of the same type instead of creating new instances and conversion, so that way it is much more optimal.

-----

In addition, in this line of codes.

https://github.com/ademolguner/RepoDbExample/blob/ce1222c83dcc6007a7e4da395cab5fa6037f3eca/RepoDbExample/RepoDbExample.Core/DataAccess/RepoDb/DbRepositoryBase.cs#L64

You can utilize the [BatchQuery](http://repodb.net/operation/batchquery) so you only fetch the necessary rows from the DB, rather than doing a post process in the client.

```csharp
public List<TEntity> GetList(int skip, int count)
{
	using var conn = new DbConnection().CreateConnection().EnsureOpen();
	List<TEntity> data = conn.BatchQuery<TEntity>(page: skip, rowsPerBatch: count, orderBy: orderBy, where: (QueryField)null).AsList();
	return data;
}
```

**Comment by ademolguner** [comment]
Hi, I'll edit the code. Thank you.

**Comment by ademolguner** [comment]
> Hi, I saw in your code that you post-process the data in the client. You can actually improve this query.
> 
> https://github.com/ademolguner/RepoDbExample/blob/ce1222c83dcc6007a7e4da395cab5fa6037f3eca/RepoDbExample/RepoDbExample.Core/DataAccess/RepoDb/DbRepositoryBase.cs#L57
> 
> Using this one.
> 
> ```cs
> List<TEntity> data = conn.QueryAll<TEntity>(rows: count).AsList();
> ```
> 
> I would highly recommend to always use the `AsList()` extended method over `ToList()`. It try to cast first if the objects are of the same type instead of creating new instances and conversion, so that way it is much more optimal.
> 
> In addition, in this line of codes.
> 
> https://github.com/ademolguner/RepoDbExample/blob/ce1222c83dcc6007a7e4da395cab5fa6037f3eca/RepoDbExample/RepoDbExample.Core/DataAccess/RepoDb/DbRepositoryBase.cs#L64
> 
> You can utilize the [BatchQuery](http://repodb.net/operation/batchquery) so you only fetch the necessary rows from the DB, rather than doing a post process in the client.
> 
> ```cs
> public List<TEntity> GetList(int skip, int count)
> {
> 	using var conn = new DbConnection().CreateConnection().EnsureOpen();
> 	List<TEntity> data = conn.BatchQuery<TEntity>(page: skip, rowsPerBatch: count, orderBy: orderBy, where: (QueryField)null).AsList();
> 	return data;
> }
> ```

**Comment by ademolguner** [comment]
> Hi, I saw in your code that you post-process the data in the client. You can actually improve this query.
> 
> https://github.com/ademolguner/RepoDbExample/blob/ce1222c83dcc6007a7e4da395cab5fa6037f3eca/RepoDbExample/RepoDbExample.Core/DataAccess/RepoDb/DbRepositoryBase.cs#L57
> 
> Using this one.
> 
> ```cs
> List<TEntity> data = conn.QueryAll<TEntity>(rows: count).AsList();
> ```
> 
> I would highly recommend to always use the `AsList()` extended method over `ToList()`. It try to cast first if the objects are of the same type instead of creating new instances and conversion, so that way it is much more optimal.
> 
> In addition, in this line of codes.
> 
> https://github.com/ademolguner/RepoDbExample/blob/ce1222c83dcc6007a7e4da395cab5fa6037f3eca/RepoDbExample/RepoDbExample.Core/DataAccess/RepoDb/DbRepositoryBase.cs#L64
> 
> You can utilize the [BatchQuery](http://repodb.net/operation/batchquery) so you only fetch the necessary rows from the DB, rather than doing a post process in the client.
> 
> ```cs
> public List<TEntity> GetList(int skip, int count)
> {
> 	using var conn = new DbConnection().CreateConnection().EnsureOpen();
> 	List<TEntity> data = conn.BatchQuery<TEntity>(page: skip, rowsPerBatch: count, orderBy: orderBy, where: (QueryField)null).AsList();
> 	return data;
> }
> ```

Hi, I'll edit the code. Thank you.
